/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Config = t.iface([], {
  "isInterpreter": "boolean",
  "listenerVolume": "number",
  "startAudioMuted": "boolean",
  "startVideoMuted": "boolean",
  "reuseListenerPin": "boolean",
  "roleIndicator": "boolean",
  "filterActiveLanguages": "boolean",
  "monitorSubRooms": t.iface([], {
    "enabled": "boolean",
    "rescanInterval": "number",
    "guestPin": "string",
  }),
  "languages": t.array(t.tuple("string", "string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Config,
};
export default exportedTypeSuite;
